version: 2.0
jobs:
    "ruby-2.2":
        docker:
            - image: circleci/ruby:2.2
        steps:
            - checkout
            - run: bundle install
            - run: bundle exec rake test TESTOPTS="--ci-dir=$CIRCLE_TEST_REPORTS/reports"
    "ruby-2.3":
        docker:
            - image: circleci/ruby:2.3
        steps:
            - checkout
            - run: bundle install
            - run: bundle exec rake test TESTOPTS="--ci-dir=$CIRCLE_TEST_REPORTS/reports"
    "ruby-2.4":
        docker:
            - image: circleci/ruby:2.4
        steps:
            - checkout
            - run: bundle install
            - run: bundle exec rake test TESTOPTS="--ci-dir=$CIRCLE_TEST_REPORTS/reports"
workflows:
    version: 2
    build:
        jobs:
            - "ruby-2.2"
            - "ruby-2.3"
            - "ruby-2.4"
